############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Registration"
url = "/registration"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "Gallery"
url = "/gallery"
weight = 4

# [[main]]
# weight = 4
# name = "Pages"

[[main]]
name = "About"
url = "/about"
weight = 5

[[main]]
# parent = "Pages"
name = "Contact"
url = "/contactus"
weight = 6

[[main]]
# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Registration"
url = "/registration"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
